with Flyology_SIMD.Backends.Native;

package body Construction_Codegen_Probe is
   package Native renames Flyology_SIMD.Backends.Native;

   function Zero_U8 return Flyology_SIMD.U8x16 is (Native.Zero);
   function Splat_U8 (Value : Flyology_SIMD.U8) return Flyology_SIMD.U8x16 is (Native.Splat (Value));
   function Zero_I8 return Flyology_SIMD.I8x16 is (Native.Zero);
   function Splat_I8 (Value : Flyology_SIMD.I8) return Flyology_SIMD.I8x16 is (Native.Splat (Value));
   function Zero_U16 return Flyology_SIMD.U16x8 is (Native.Zero);
   function Splat_U16 (Value : Flyology_SIMD.U16) return Flyology_SIMD.U16x8 is (Native.Splat (Value));
   function Zero_I16 return Flyology_SIMD.I16x8 is (Native.Zero);
   function Splat_I16 (Value : Flyology_SIMD.I16) return Flyology_SIMD.I16x8 is (Native.Splat (Value));
   function Zero_U32 return Flyology_SIMD.U32x4 is (Native.Zero);
   function Splat_U32 (Value : Flyology_SIMD.U32) return Flyology_SIMD.U32x4 is (Native.Splat (Value));
   function Zero_I32 return Flyology_SIMD.I32x4 is (Native.Zero);
   function Splat_I32 (Value : Flyology_SIMD.I32) return Flyology_SIMD.I32x4 is (Native.Splat (Value));
   function Zero_U64 return Flyology_SIMD.U64x2 is (Native.Zero);
   function Splat_U64 (Value : Flyology_SIMD.U64) return Flyology_SIMD.U64x2 is (Native.Splat (Value));
   function Zero_I64 return Flyology_SIMD.I64x2 is (Native.Zero);
   function Splat_I64 (Value : Flyology_SIMD.I64) return Flyology_SIMD.I64x2 is (Native.Splat (Value));
   function Zero_F32 return Flyology_SIMD.F32x4 is (Native.Zero);
   function Splat_F32 (Value : Flyology_SIMD.F32) return Flyology_SIMD.F32x4 is (Native.Splat (Value));
   function Zero_F64 return Flyology_SIMD.F64x2 is (Native.Zero);
   function Splat_F64 (Value : Flyology_SIMD.F64) return Flyology_SIMD.F64x2 is (Native.Splat (Value));

   function Round_Trip_U8 (Values : Flyology_SIMD.Lane_Values_8x16) return Flyology_SIMD.Lane_Values_8x16 is (Native.To_Lanes (Native.From_Lanes (Values)));
   function Extract_U8 (Value : Flyology_SIMD.U8x16; Lane : Flyology_SIMD.Lane_Index_8x16) return Flyology_SIMD.U8 is (Native.Extract (Value, Lane));
   function Replace_U8 (Value : Flyology_SIMD.U8x16; Lane : Flyology_SIMD.Lane_Index_8x16; With_Value : Flyology_SIMD.U8) return Flyology_SIMD.U8x16 is (Native.Replace (Value, Lane, With_Value));
   function Round_Trip_I8 (Values : Flyology_SIMD.Lane_Values_I8x16) return Flyology_SIMD.Lane_Values_I8x16 is (Native.To_Lanes (Native.From_Lanes (Values)));
   function Extract_I8 (Value : Flyology_SIMD.I8x16; Lane : Flyology_SIMD.Lane_Index_8x16) return Flyology_SIMD.I8 is (Native.Extract (Value, Lane));
   function Replace_I8 (Value : Flyology_SIMD.I8x16; Lane : Flyology_SIMD.Lane_Index_8x16; With_Value : Flyology_SIMD.I8) return Flyology_SIMD.I8x16 is (Native.Replace (Value, Lane, With_Value));
   function Round_Trip_U16 (Values : Flyology_SIMD.Lane_Values_U16x8) return Flyology_SIMD.Lane_Values_U16x8 is (Native.To_Lanes (Native.From_Lanes (Values)));
   function Extract_U16 (Value : Flyology_SIMD.U16x8; Lane : Flyology_SIMD.Lane_Index_16x8) return Flyology_SIMD.U16 is (Native.Extract (Value, Lane));
   function Replace_U16 (Value : Flyology_SIMD.U16x8; Lane : Flyology_SIMD.Lane_Index_16x8; With_Value : Flyology_SIMD.U16) return Flyology_SIMD.U16x8 is (Native.Replace (Value, Lane, With_Value));
   function Round_Trip_I16 (Values : Flyology_SIMD.Lane_Values_I16x8) return Flyology_SIMD.Lane_Values_I16x8 is (Native.To_Lanes (Native.From_Lanes (Values)));
   function Extract_I16 (Value : Flyology_SIMD.I16x8; Lane : Flyology_SIMD.Lane_Index_16x8) return Flyology_SIMD.I16 is (Native.Extract (Value, Lane));
   function Replace_I16 (Value : Flyology_SIMD.I16x8; Lane : Flyology_SIMD.Lane_Index_16x8; With_Value : Flyology_SIMD.I16) return Flyology_SIMD.I16x8 is (Native.Replace (Value, Lane, With_Value));
   function Round_Trip_U32 (Values : Flyology_SIMD.Lane_Values_U32x4) return Flyology_SIMD.Lane_Values_U32x4 is (Native.To_Lanes (Native.From_Lanes (Values)));
   function Extract_U32 (Value : Flyology_SIMD.U32x4; Lane : Flyology_SIMD.Lane_Index_32x4) return Flyology_SIMD.U32 is (Native.Extract (Value, Lane));
   function Replace_U32 (Value : Flyology_SIMD.U32x4; Lane : Flyology_SIMD.Lane_Index_32x4; With_Value : Flyology_SIMD.U32) return Flyology_SIMD.U32x4 is (Native.Replace (Value, Lane, With_Value));
   function Round_Trip_I32 (Values : Flyology_SIMD.Lane_Values_I32x4) return Flyology_SIMD.Lane_Values_I32x4 is (Native.To_Lanes (Native.From_Lanes (Values)));
   function Extract_I32 (Value : Flyology_SIMD.I32x4; Lane : Flyology_SIMD.Lane_Index_32x4) return Flyology_SIMD.I32 is (Native.Extract (Value, Lane));
   function Replace_I32 (Value : Flyology_SIMD.I32x4; Lane : Flyology_SIMD.Lane_Index_32x4; With_Value : Flyology_SIMD.I32) return Flyology_SIMD.I32x4 is (Native.Replace (Value, Lane, With_Value));
   function Round_Trip_U64 (Values : Flyology_SIMD.Lane_Values_U64x2) return Flyology_SIMD.Lane_Values_U64x2 is (Native.To_Lanes (Native.From_Lanes (Values)));
   function Extract_U64 (Value : Flyology_SIMD.U64x2; Lane : Flyology_SIMD.Lane_Index_64x2) return Flyology_SIMD.U64 is (Native.Extract (Value, Lane));
   function Replace_U64 (Value : Flyology_SIMD.U64x2; Lane : Flyology_SIMD.Lane_Index_64x2; With_Value : Flyology_SIMD.U64) return Flyology_SIMD.U64x2 is (Native.Replace (Value, Lane, With_Value));
   function Round_Trip_I64 (Values : Flyology_SIMD.Lane_Values_I64x2) return Flyology_SIMD.Lane_Values_I64x2 is (Native.To_Lanes (Native.From_Lanes (Values)));
   function Extract_I64 (Value : Flyology_SIMD.I64x2; Lane : Flyology_SIMD.Lane_Index_64x2) return Flyology_SIMD.I64 is (Native.Extract (Value, Lane));
   function Replace_I64 (Value : Flyology_SIMD.I64x2; Lane : Flyology_SIMD.Lane_Index_64x2; With_Value : Flyology_SIMD.I64) return Flyology_SIMD.I64x2 is (Native.Replace (Value, Lane, With_Value));
   function Round_Trip_F32 (Values : Flyology_SIMD.Lane_Values_F32x4) return Flyology_SIMD.Lane_Values_F32x4 is (Native.To_Lanes (Native.From_Lanes (Values)));
   function Extract_F32 (Value : Flyology_SIMD.F32x4; Lane : Flyology_SIMD.Lane_Index_32x4) return Flyology_SIMD.F32 is (Native.Extract (Value, Lane));
   function Replace_F32 (Value : Flyology_SIMD.F32x4; Lane : Flyology_SIMD.Lane_Index_32x4; With_Value : Flyology_SIMD.F32) return Flyology_SIMD.F32x4 is (Native.Replace (Value, Lane, With_Value));
   function Round_Trip_F64 (Values : Flyology_SIMD.Lane_Values_F64x2) return Flyology_SIMD.Lane_Values_F64x2 is (Native.To_Lanes (Native.From_Lanes (Values)));
   function Extract_F64 (Value : Flyology_SIMD.F64x2; Lane : Flyology_SIMD.Lane_Index_64x2) return Flyology_SIMD.F64 is (Native.Extract (Value, Lane));
   function Replace_F64 (Value : Flyology_SIMD.F64x2; Lane : Flyology_SIMD.Lane_Index_64x2; With_Value : Flyology_SIMD.F64) return Flyology_SIMD.F64x2 is (Native.Replace (Value, Lane, With_Value));
end Construction_Codegen_Probe;
