with Flyology_SIMD.Wide;

package Wide_Memory_Codegen_Probe is
   package SIMD renames Flyology_SIMD;
   package Wide renames Flyology_SIMD.Wide;
   function u8_load (Data : SIMD.Byte_Array; Start : Natural) return Wide.U8x32;
   procedure u8_store (Data : in out SIMD.Byte_Array; Start : Natural; Value : Wide.U8x32);
   function u8_load_unaligned (Data : SIMD.Byte_Array; Start : Natural) return Wide.U8x32;
   procedure u8_store_unaligned (Data : in out SIMD.Byte_Array; Start : Natural; Value : Wide.U8x32);
   function u8_load_aligned (Data : SIMD.Byte_Array; Start : Natural) return Wide.U8x32;
   procedure u8_store_aligned (Data : in out SIMD.Byte_Array; Start : Natural; Value : Wide.U8x32);
   function u8_load_partial (Data : SIMD.Byte_Array; Start : Natural; Count : Wide.Lane_Count_8x32) return Wide.U8x32;
   procedure u8_store_partial (Data : in out SIMD.Byte_Array; Start : Natural; Count : Wide.Lane_Count_8x32; Value : Wide.U8x32);
   function i8_load (Data : SIMD.I8_Array; Start : Natural) return Wide.I8x32;
   procedure i8_store (Data : in out SIMD.I8_Array; Start : Natural; Value : Wide.I8x32);
   function i8_load_unaligned (Data : SIMD.I8_Array; Start : Natural) return Wide.I8x32;
   procedure i8_store_unaligned (Data : in out SIMD.I8_Array; Start : Natural; Value : Wide.I8x32);
   function i8_load_aligned (Data : SIMD.I8_Array; Start : Natural) return Wide.I8x32;
   procedure i8_store_aligned (Data : in out SIMD.I8_Array; Start : Natural; Value : Wide.I8x32);
   function i8_load_partial (Data : SIMD.I8_Array; Start : Natural; Count : Wide.Lane_Count_8x32) return Wide.I8x32;
   procedure i8_store_partial (Data : in out SIMD.I8_Array; Start : Natural; Count : Wide.Lane_Count_8x32; Value : Wide.I8x32);
   function u16_load (Data : SIMD.U16_Array; Start : Natural) return Wide.U16x16;
   procedure u16_store (Data : in out SIMD.U16_Array; Start : Natural; Value : Wide.U16x16);
   function u16_load_unaligned (Data : SIMD.U16_Array; Start : Natural) return Wide.U16x16;
   procedure u16_store_unaligned (Data : in out SIMD.U16_Array; Start : Natural; Value : Wide.U16x16);
   function u16_load_aligned (Data : SIMD.U16_Array; Start : Natural) return Wide.U16x16;
   procedure u16_store_aligned (Data : in out SIMD.U16_Array; Start : Natural; Value : Wide.U16x16);
   function u16_load_partial (Data : SIMD.U16_Array; Start : Natural; Count : Wide.Lane_Count_16x16) return Wide.U16x16;
   procedure u16_store_partial (Data : in out SIMD.U16_Array; Start : Natural; Count : Wide.Lane_Count_16x16; Value : Wide.U16x16);
   function i16_load (Data : SIMD.I16_Array; Start : Natural) return Wide.I16x16;
   procedure i16_store (Data : in out SIMD.I16_Array; Start : Natural; Value : Wide.I16x16);
   function i16_load_unaligned (Data : SIMD.I16_Array; Start : Natural) return Wide.I16x16;
   procedure i16_store_unaligned (Data : in out SIMD.I16_Array; Start : Natural; Value : Wide.I16x16);
   function i16_load_aligned (Data : SIMD.I16_Array; Start : Natural) return Wide.I16x16;
   procedure i16_store_aligned (Data : in out SIMD.I16_Array; Start : Natural; Value : Wide.I16x16);
   function i16_load_partial (Data : SIMD.I16_Array; Start : Natural; Count : Wide.Lane_Count_16x16) return Wide.I16x16;
   procedure i16_store_partial (Data : in out SIMD.I16_Array; Start : Natural; Count : Wide.Lane_Count_16x16; Value : Wide.I16x16);
   function u32_load (Data : SIMD.U32_Array; Start : Natural) return Wide.U32x8;
   procedure u32_store (Data : in out SIMD.U32_Array; Start : Natural; Value : Wide.U32x8);
   function u32_load_unaligned (Data : SIMD.U32_Array; Start : Natural) return Wide.U32x8;
   procedure u32_store_unaligned (Data : in out SIMD.U32_Array; Start : Natural; Value : Wide.U32x8);
   function u32_load_aligned (Data : SIMD.U32_Array; Start : Natural) return Wide.U32x8;
   procedure u32_store_aligned (Data : in out SIMD.U32_Array; Start : Natural; Value : Wide.U32x8);
   function u32_load_partial (Data : SIMD.U32_Array; Start : Natural; Count : Wide.Lane_Count_32x8) return Wide.U32x8;
   procedure u32_store_partial (Data : in out SIMD.U32_Array; Start : Natural; Count : Wide.Lane_Count_32x8; Value : Wide.U32x8);
   function i32_load (Data : SIMD.I32_Array; Start : Natural) return Wide.I32x8;
   procedure i32_store (Data : in out SIMD.I32_Array; Start : Natural; Value : Wide.I32x8);
   function i32_load_unaligned (Data : SIMD.I32_Array; Start : Natural) return Wide.I32x8;
   procedure i32_store_unaligned (Data : in out SIMD.I32_Array; Start : Natural; Value : Wide.I32x8);
   function i32_load_aligned (Data : SIMD.I32_Array; Start : Natural) return Wide.I32x8;
   procedure i32_store_aligned (Data : in out SIMD.I32_Array; Start : Natural; Value : Wide.I32x8);
   function i32_load_partial (Data : SIMD.I32_Array; Start : Natural; Count : Wide.Lane_Count_32x8) return Wide.I32x8;
   procedure i32_store_partial (Data : in out SIMD.I32_Array; Start : Natural; Count : Wide.Lane_Count_32x8; Value : Wide.I32x8);
   function u64_load (Data : SIMD.U64_Array; Start : Natural) return Wide.U64x4;
   procedure u64_store (Data : in out SIMD.U64_Array; Start : Natural; Value : Wide.U64x4);
   function u64_load_unaligned (Data : SIMD.U64_Array; Start : Natural) return Wide.U64x4;
   procedure u64_store_unaligned (Data : in out SIMD.U64_Array; Start : Natural; Value : Wide.U64x4);
   function u64_load_aligned (Data : SIMD.U64_Array; Start : Natural) return Wide.U64x4;
   procedure u64_store_aligned (Data : in out SIMD.U64_Array; Start : Natural; Value : Wide.U64x4);
   function u64_load_partial (Data : SIMD.U64_Array; Start : Natural; Count : Wide.Lane_Count_64x4) return Wide.U64x4;
   procedure u64_store_partial (Data : in out SIMD.U64_Array; Start : Natural; Count : Wide.Lane_Count_64x4; Value : Wide.U64x4);
   function i64_load (Data : SIMD.I64_Array; Start : Natural) return Wide.I64x4;
   procedure i64_store (Data : in out SIMD.I64_Array; Start : Natural; Value : Wide.I64x4);
   function i64_load_unaligned (Data : SIMD.I64_Array; Start : Natural) return Wide.I64x4;
   procedure i64_store_unaligned (Data : in out SIMD.I64_Array; Start : Natural; Value : Wide.I64x4);
   function i64_load_aligned (Data : SIMD.I64_Array; Start : Natural) return Wide.I64x4;
   procedure i64_store_aligned (Data : in out SIMD.I64_Array; Start : Natural; Value : Wide.I64x4);
   function i64_load_partial (Data : SIMD.I64_Array; Start : Natural; Count : Wide.Lane_Count_64x4) return Wide.I64x4;
   procedure i64_store_partial (Data : in out SIMD.I64_Array; Start : Natural; Count : Wide.Lane_Count_64x4; Value : Wide.I64x4);
   function f32_load (Data : SIMD.F32_Array; Start : Natural) return Wide.F32x8;
   procedure f32_store (Data : in out SIMD.F32_Array; Start : Natural; Value : Wide.F32x8);
   function f32_load_unaligned (Data : SIMD.F32_Array; Start : Natural) return Wide.F32x8;
   procedure f32_store_unaligned (Data : in out SIMD.F32_Array; Start : Natural; Value : Wide.F32x8);
   function f32_load_aligned (Data : SIMD.F32_Array; Start : Natural) return Wide.F32x8;
   procedure f32_store_aligned (Data : in out SIMD.F32_Array; Start : Natural; Value : Wide.F32x8);
   function f32_load_partial (Data : SIMD.F32_Array; Start : Natural; Count : Wide.Lane_Count_32x8) return Wide.F32x8;
   procedure f32_store_partial (Data : in out SIMD.F32_Array; Start : Natural; Count : Wide.Lane_Count_32x8; Value : Wide.F32x8);
   function f64_load (Data : SIMD.F64_Array; Start : Natural) return Wide.F64x4;
   procedure f64_store (Data : in out SIMD.F64_Array; Start : Natural; Value : Wide.F64x4);
   function f64_load_unaligned (Data : SIMD.F64_Array; Start : Natural) return Wide.F64x4;
   procedure f64_store_unaligned (Data : in out SIMD.F64_Array; Start : Natural; Value : Wide.F64x4);
   function f64_load_aligned (Data : SIMD.F64_Array; Start : Natural) return Wide.F64x4;
   procedure f64_store_aligned (Data : in out SIMD.F64_Array; Start : Natural; Value : Wide.F64x4);
   function f64_load_partial (Data : SIMD.F64_Array; Start : Natural; Count : Wide.Lane_Count_64x4) return Wide.F64x4;
   procedure f64_store_partial (Data : in out SIMD.F64_Array; Start : Natural; Count : Wide.Lane_Count_64x4; Value : Wide.F64x4);
end Wide_Memory_Codegen_Probe;
