--  Generated by scripts/generate_conversion_tests.py; do not edit.
with Ada.Command_Line;
with Ada.Text_IO;
with Ada.Unchecked_Conversion;
with Interfaces;
with Flyology_SIMD;
with Flyology_SIMD.Backends.Native;

procedure Conversion_Tests is
   use Ada.Text_IO;
   use Flyology_SIMD;
   use type Interfaces.Unsigned_8;
   use type Interfaces.Unsigned_16;
   use type Interfaces.Unsigned_32;
   use type Interfaces.Unsigned_64;
   use type Interfaces.Integer_8;
   use type Interfaces.Integer_16;
   use type Interfaces.Integer_32;
   use type Interfaces.Integer_64;
   use type Interfaces.IEEE_Float_32;
   use type Interfaces.IEEE_Float_64;

   Seed : constant Interfaces.Unsigned_64 := 16#C045_7A57_1280_0A11#;
   State : Interfaces.Unsigned_64 := Seed;
   Failures : Natural := 0;

   procedure Check (Condition : Boolean; Message : String) is
   begin
      if not Condition then Failures := Failures + 1; Put_Line ("FAIL: " & Message); end if;
   end Check;

   function Next_U64 return Interfaces.Unsigned_64 is
   begin
      State := State xor Interfaces.Shift_Left (State, 13);
      State := State xor Interfaces.Shift_Right (State, 7);
      State := State xor Interfaces.Shift_Left (State, 17);
      return State;
   end Next_U64;

   function I8_Of_Bits is new Ada.Unchecked_Conversion (U8, I8);
   function I16_Of_Bits is new Ada.Unchecked_Conversion (U16, I16);
   function I32_Of_Bits is new Ada.Unchecked_Conversion (U32, I32);
   function I64_Of_Bits is new Ada.Unchecked_Conversion (U64, I64);
   function U16_Of_Bits is new Ada.Unchecked_Conversion (I16, U16);
   function U32_Of_Bits is new Ada.Unchecked_Conversion (I32, U32);
   function U64_Of_Bits is new Ada.Unchecked_Conversion (I64, U64);
   function F32_Of_Bits is new Ada.Unchecked_Conversion (U32, F32);
   function F64_Of_Bits is new Ada.Unchecked_Conversion (U64, F64);
   function U32_Of_Bits is new Ada.Unchecked_Conversion (F32, U32);
   function U64_Of_Bits is new Ada.Unchecked_Conversion (F64, U64);

   function Cast_U8_To_I8 is new Ada.Unchecked_Conversion (U8, I8);
   function Cast_I8_To_U8 is new Ada.Unchecked_Conversion (I8, U8);
   function Cast_U16_To_I16 is new Ada.Unchecked_Conversion (U16, I16);
   function Cast_I16_To_U16 is new Ada.Unchecked_Conversion (I16, U16);
   function Cast_U32_To_I32 is new Ada.Unchecked_Conversion (U32, I32);
   function Cast_U32_To_F32 is new Ada.Unchecked_Conversion (U32, F32);
   function Cast_I32_To_U32 is new Ada.Unchecked_Conversion (I32, U32);
   function Cast_I32_To_F32 is new Ada.Unchecked_Conversion (I32, F32);
   function Cast_F32_To_U32 is new Ada.Unchecked_Conversion (F32, U32);
   function Cast_F32_To_I32 is new Ada.Unchecked_Conversion (F32, I32);
   function Cast_U64_To_I64 is new Ada.Unchecked_Conversion (U64, I64);
   function Cast_U64_To_F64 is new Ada.Unchecked_Conversion (U64, F64);
   function Cast_I64_To_U64 is new Ada.Unchecked_Conversion (I64, U64);
   function Cast_I64_To_F64 is new Ada.Unchecked_Conversion (I64, F64);
   function Cast_F64_To_U64 is new Ada.Unchecked_Conversion (F64, U64);
   function Cast_F64_To_I64 is new Ada.Unchecked_Conversion (F64, I64);

   function Same (Left, Right : F32) return Boolean is (U32_Of_Bits (Left) = U32_Of_Bits (Right));
   function Same (Left, Right : F64) return Boolean is (U64_Of_Bits (Left) = U64_Of_Bits (Right));
   function Same (Left, Right : U8) return Boolean is (Left = Right);
   function Same (Left, Right : I8) return Boolean is (Left = Right);
   function Same (Left, Right : U16) return Boolean is (Left = Right);
   function Same (Left, Right : I16) return Boolean is (Left = Right);
   function Same (Left, Right : U32) return Boolean is (Left = Right);
   function Same (Left, Right : I32) return Boolean is (Left = Right);
   function Same (Left, Right : U64) return Boolean is (Left = Right);
   function Same (Left, Right : I64) return Boolean is (Left = Right);

   function Is_NaN (Value : F64) return Boolean is
      Bits : constant U64 := U64_Of_Bits (Value);
   begin
      return (Bits and 16#7FF0_0000_0000_0000#) = 16#7FF0_0000_0000_0000#
        and then (Bits and 16#000F_FFFF_FFFF_FFFF#) /= 0;
   end Is_NaN;
   function Is_NaN (Value : F32) return Boolean is
      Bits : constant U32 := U32_Of_Bits (Value);
   begin
      return (Bits and 16#7F80_0000#) = 16#7F80_0000#
        and then (Bits and 16#007F_FFFF#) /= 0;
   end Is_NaN;

   function Random_U8x16 return U8x16 is
      Values : Lane_Values_8x16;
   begin
      for Lane in Lane_Index_8x16 loop Values (Lane) := U8 (Next_U64 and U64 (U8'Last)); end loop;
      return From_Lanes (Values);
   end Random_U8x16;

   function Random_I8x16 return I8x16 is
      Values : Lane_Values_I8x16;
   begin
      for Lane in Lane_Index_8x16 loop Values (Lane) := I8_Of_Bits (U8 (Next_U64 and U64 (U8'Last))); end loop;
      return From_Lanes (Values);
   end Random_I8x16;

   function Random_U16x8 return U16x8 is
      Values : Lane_Values_U16x8;
   begin
      for Lane in Lane_Index_16x8 loop Values (Lane) := U16 (Next_U64 and U64 (U16'Last)); end loop;
      return From_Lanes (Values);
   end Random_U16x8;

   function Random_I16x8 return I16x8 is
      Values : Lane_Values_I16x8;
   begin
      for Lane in Lane_Index_16x8 loop Values (Lane) := I16_Of_Bits (U16 (Next_U64 and U64 (U16'Last))); end loop;
      return From_Lanes (Values);
   end Random_I16x8;

   function Random_U32x4 return U32x4 is
      Values : Lane_Values_U32x4;
   begin
      for Lane in Lane_Index_32x4 loop Values (Lane) := U32 (Next_U64 and U64 (U32'Last)); end loop;
      return From_Lanes (Values);
   end Random_U32x4;

   function Random_I32x4 return I32x4 is
      Values : Lane_Values_I32x4;
   begin
      for Lane in Lane_Index_32x4 loop Values (Lane) := I32_Of_Bits (U32 (Next_U64 and U64 (U32'Last))); end loop;
      return From_Lanes (Values);
   end Random_I32x4;

   function Random_U64x2 return U64x2 is
      Values : Lane_Values_U64x2;
   begin
      for Lane in Lane_Index_64x2 loop Values (Lane) := U64 (Next_U64 and U64 (U64'Last)); end loop;
      return From_Lanes (Values);
   end Random_U64x2;

   function Random_I64x2 return I64x2 is
      Values : Lane_Values_I64x2;
   begin
      for Lane in Lane_Index_64x2 loop Values (Lane) := I64_Of_Bits (U64 (Next_U64 and U64 (U64'Last))); end loop;
      return From_Lanes (Values);
   end Random_I64x2;

   function Random_F32x4 return F32x4 is
      Values : Lane_Values_F32x4;
   begin
      for Lane in Lane_Index_32x4 loop Values (Lane) := F32 (Interfaces.Integer_32 (Next_U64 mod 2_000_001) - 1_000_000) / 16.0; end loop;
      return From_Lanes (Values);
   end Random_F32x4;

   function Random_F64x2 return F64x2 is
      Values : Lane_Values_F64x2;
   begin
      for Lane in Lane_Index_64x2 loop Values (Lane) := F64 (Interfaces.Integer_64 (Next_U64 mod 2_000_001) - 1_000_000) / 16.0; end loop;
      return From_Lanes (Values);
   end Random_F64x2;

   function Random_Narrow_F64x2 return F64x2 is
      Values : Lane_Values_F64x2;
   begin
      for Lane in Lane_Index_64x2 loop
         declare
            Sign_And_Fraction : constant U64 := Next_U64;
            Unbiased_Exponent : constant Integer := Integer (Next_U64 mod 288) - 160;
            Bits : constant U64 :=
              (Sign_And_Fraction and 16#800F_FFFF_FFFF_FFFF#)
              or Interfaces.Shift_Left (U64 (Unbiased_Exponent + 1_023), 52);
         begin
            Values (Lane) := F64_Of_Bits (Bits);
         end;
      end loop;
      return From_Lanes (Values);
   end Random_Narrow_F64x2;

   function Oracle_Narrow_Truncate_U16x8_To_U8x16 (Item : U16) return U8 is (U8 (Item and U16 (U8'Last)));
   function Oracle_Narrow_Saturate_U16x8_To_U8x16 (Item : U16) return U8 is ((if Item > U16 (U8'Last) then U8'Last else U8 (Item)));
   function Oracle_Narrow_Truncate_I16x8_To_I8x16 (Item : I16) return I8 is (I8_Of_Bits (U8 (U16_Of_Bits (Item) and U16 (U8'Last))));
   function Oracle_Narrow_Saturate_I16x8_To_I8x16 (Item : I16) return I8 is ((if Item < I16 (I8'First) then I8'First elsif Item > I16 (I8'Last) then I8'Last else I8 (Item)));
   function Oracle_Narrow_Truncate_U32x4_To_U16x8 (Item : U32) return U16 is (U16 (Item and U32 (U16'Last)));
   function Oracle_Narrow_Saturate_U32x4_To_U16x8 (Item : U32) return U16 is ((if Item > U32 (U16'Last) then U16'Last else U16 (Item)));
   function Oracle_Narrow_Truncate_I32x4_To_I16x8 (Item : I32) return I16 is (I16_Of_Bits (U16 (U32_Of_Bits (Item) and U32 (U16'Last))));
   function Oracle_Narrow_Saturate_I32x4_To_I16x8 (Item : I32) return I16 is ((if Item < I32 (I16'First) then I16'First elsif Item > I32 (I16'Last) then I16'Last else I16 (Item)));
   function Oracle_Narrow_Truncate_U64x2_To_U32x4 (Item : U64) return U32 is (U32 (Item and U64 (U32'Last)));
   function Oracle_Narrow_Saturate_U64x2_To_U32x4 (Item : U64) return U32 is ((if Item > U64 (U32'Last) then U32'Last else U32 (Item)));
   function Oracle_Narrow_Truncate_I64x2_To_I32x4 (Item : I64) return I32 is (I32_Of_Bits (U32 (U64_Of_Bits (Item) and U64 (U32'Last))));
   function Oracle_Narrow_Saturate_I64x2_To_I32x4 (Item : I64) return I32 is ((if Item < I64 (I32'First) then I32'First elsif Item > I64 (I32'Last) then I32'Last else I32 (Item)));
   function Oracle_Narrow_Saturate_I16x8_To_U8x16 (Item : I16) return U8 is (if Item < 0 then 0 elsif Item > I16 (U8'Last) then U8'Last else U8 (Item));
   function Oracle_Narrow_Saturate_I32x4_To_U16x8 (Item : I32) return U16 is (if Item < 0 then 0 elsif Item > I32 (U16'Last) then U16'Last else U16 (Item));
   function Oracle_Narrow_Saturate_I64x2_To_U32x4 (Item : I64) return U32 is (if Item < 0 then 0 elsif Item > I64 (U32'Last) then U32'Last else U32 (Item));
   function Oracle_Narrow_Round_F64x2_To_F32x4 (Item : F64) return F32 is
      Bits : constant U64 := U64_Of_Bits (Item);
      Sign : constant U32 :=
        (if (Bits and 16#8000_0000_0000_0000#) = 0 then 0 else 16#8000_0000#);
      Encoded_Exponent : constant Natural :=
        Natural (Interfaces.Shift_Right (Bits, 52) and 16#7FF#);
      Fraction : constant U64 := Bits and 16#000F_FFFF_FFFF_FFFF#;

      function Round_Right (Value : U64; Count : Positive) return U64 is
         Quotient : constant U64 := Interfaces.Shift_Right (Value, Count);
         Half : constant U64 := Interfaces.Shift_Left (1, Count - 1);
         Remainder : constant U64 :=
           Value and (Interfaces.Shift_Left (1, Count) - 1);
      begin
         if Remainder > Half
           or else (Remainder = Half and then (Quotient and 1) /= 0)
         then
            return Quotient + 1;
         else
            return Quotient;
         end if;
      end Round_Right;

      Exponent : Integer;
      Significant : U64;
      Rounded : U64;
   begin
      if Encoded_Exponent = 0 then
         return F32_Of_Bits (Sign);
      elsif Encoded_Exponent = 16#7FF# then
         if Fraction = 0 then
            return F32_Of_Bits (Sign or 16#7F80_0000#);
         else
            return F32_Of_Bits (Sign or 16#7FC0_0000#);
         end if;
      end if;

      Exponent := Encoded_Exponent - 1_023;
      Significant := 16#0010_0000_0000_0000# or Fraction;
      if Exponent >= -126 then
         Rounded := Round_Right (Significant, 29);
         if Rounded = 16#0100_0000# then
            Rounded := 16#0080_0000#;
            Exponent := Exponent + 1;
         end if;
         if Exponent > 127 then
            return F32_Of_Bits (Sign or 16#7F80_0000#);
         end if;
         return F32_Of_Bits
           (Sign or Interfaces.Shift_Left (U32 (Exponent + 127), 23)
            or U32 (Rounded - 16#0080_0000#));
      end if;

      declare
         Shift : constant Positive := -Exponent - 97;
      begin
         if Shift > 53 then
            return F32_Of_Bits (Sign);
         end if;
         Rounded := Round_Right (Significant, Shift);
         return F32_Of_Bits (Sign or U32 (Rounded));
      end;
   end Oracle_Narrow_Round_F64x2_To_F32x4;

   procedure Test_F32_Widen_Edges is
      Zeros_And_Infinities : constant F32x4 := From_Lanes
        ([F32_Of_Bits (16#0000_0000#), F32_Of_Bits (16#8000_0000#),
          F32_Of_Bits (16#7F80_0000#), F32_Of_Bits (16#FF80_0000#)]);
      Finite_Boundaries : constant F32x4 := From_Lanes
        ([F32_Of_Bits (16#0000_0001#), F32_Of_Bits (16#007F_FFFF#),
          F32_Of_Bits (16#0080_0000#), F32_Of_Bits (16#7F7F_FFFF#)]);
      NaNs : constant F32x4 := From_Lanes
        ([F32_Of_Bits (16#7FC0_0001#), F32_Of_Bits (16#7F80_0001#),
          F32_Of_Bits (16#FFC0_0001#), F32_Of_Bits (16#FF80_0001#)]);
      type Expected_F64_Bits is array (Lane_Index_64x2) of U64;
      Expected_Zero_Low : constant Expected_F64_Bits :=
        [16#0000_0000_0000_0000#, 16#8000_0000_0000_0000#];
      Expected_Zero_High : constant Expected_F64_Bits :=
        [16#7FF0_0000_0000_0000#, 16#FFF0_0000_0000_0000#];
      Expected_Finite_Low : constant Expected_F64_Bits :=
        [16#36A0_0000_0000_0000#, 16#380F_FFFF_C000_0000#];
      Expected_Finite_High : constant Expected_F64_Bits :=
        [16#3810_0000_0000_0000#, 16#47EF_FFFF_E000_0000#];

      procedure Check_Exact
        (Value : F32x4; Expected_Low, Expected_High : Expected_F64_Bits) is
         Scalar_Low : constant F64x2 := Widen_Low (Value);
         Scalar_High : constant F64x2 := Widen_High (Value);
         Native_Low : constant F64x2 := Backends.Native.Widen_Low (Value);
         Native_High : constant F64x2 := Backends.Native.Widen_High (Value);
      begin
         for Lane in Lane_Index_64x2 loop
            Check (U64_Of_Bits (Extract (Scalar_Low, Lane)) = Expected_Low (Lane), "scalar F32 low widening edge");
            Check (U64_Of_Bits (Extract (Native_Low, Lane)) = Expected_Low (Lane), "native F32 low widening edge");
            Check (U64_Of_Bits (Extract (Scalar_High, Lane)) = Expected_High (Lane), "scalar F32 high widening edge");
            Check (U64_Of_Bits (Extract (Native_High, Lane)) = Expected_High (Lane), "native F32 high widening edge");
         end loop;
      end Check_Exact;

      Scalar_NaN_Low : constant F64x2 := Widen_Low (NaNs);
      Scalar_NaN_High : constant F64x2 := Widen_High (NaNs);
      Native_NaN_Low : constant F64x2 := Backends.Native.Widen_Low (NaNs);
      Native_NaN_High : constant F64x2 := Backends.Native.Widen_High (NaNs);
   begin
      Check_Exact (Zeros_And_Infinities, Expected_Zero_Low, Expected_Zero_High);
      Check_Exact (Finite_Boundaries, Expected_Finite_Low, Expected_Finite_High);
      for Lane in Lane_Index_64x2 loop
         Check (Is_NaN (Extract (Scalar_NaN_Low, Lane)), "scalar F32 low NaN widening");
         Check (Is_NaN (Extract (Native_NaN_Low, Lane)), "native F32 low NaN widening");
         Check (Is_NaN (Extract (Scalar_NaN_High, Lane)), "scalar F32 high NaN widening");
         Check (Is_NaN (Extract (Native_NaN_High, Lane)), "native F32 high NaN widening");
      end loop;
   end Test_F32_Widen_Edges;

   procedure Test_F64_Narrow_Edges is
      Zeros_And_Infinities_Low : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#0000_0000_0000_0000#), F64_Of_Bits (16#8000_0000_0000_0000#)]);
      Zeros_And_Infinities_High : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#7FF0_0000_0000_0000#), F64_Of_Bits (16#FFF0_0000_0000_0000#)]);
      Rounding_Low : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#3FF0_0000_1000_0000#), F64_Of_Bits (16#3FF0_0000_1000_0001#)]);
      Rounding_High : constant F64x2 := From_Lanes
        ([F64 (F32_Of_Bits (16#7F7F_FFFF#)), F64_Of_Bits (16#7FEF_FFFF_FFFF_FFFF#)]);
      Negative_Rounding_Low : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#BFF0_0000_1000_0000#), F64_Of_Bits (16#BFF0_0000_3000_0000#)]);
      Negative_Rounding_High : constant F64x2 := From_Lanes
        ([-F64 (F32_Of_Bits (16#7F7F_FFFF#)), F64_Of_Bits (16#FFEF_FFFF_FFFF_FFFF#)]);
      Subnormal_Low : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#3690_0000_0000_0000#), F64_Of_Bits (16#3690_0000_0000_0001#)]);
      Subnormal_High : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#B690_0000_0000_0000#), F64_Of_Bits (16#B690_0000_0000_0001#)]);
      Positive_Overflow_Low : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#47EF_FFFF_EFFF_FFFF#), F64_Of_Bits (16#47EF_FFFF_F000_0000#)]);
      Positive_Overflow_High : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#47EF_FFFF_F000_0001#), F64_Of_Bits (16#47EF_FFFF_E000_0000#)]);
      Negative_Overflow_Low : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#C7EF_FFFF_EFFF_FFFF#), F64_Of_Bits (16#C7EF_FFFF_F000_0000#)]);
      Negative_Overflow_High : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#C7EF_FFFF_F000_0001#), F64_Of_Bits (16#C7EF_FFFF_E000_0000#)]);
      NaN_Low : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#7FF8_0000_0000_0001#), F64_Of_Bits (16#7FF0_0000_0000_0001#)]);
      NaN_High : constant F64x2 := From_Lanes
        ([F64_Of_Bits (16#FFF8_0000_0000_0001#), F64_Of_Bits (16#FFF0_0000_0000_0001#)]);
      Exact : constant F32x4 := Narrow_Round (Zeros_And_Infinities_Low, Zeros_And_Infinities_High);
      Native_Exact : constant F32x4 := Backends.Native.Narrow_Round (Zeros_And_Infinities_Low, Zeros_And_Infinities_High);
      Rounded : constant F32x4 := Narrow_Round (Rounding_Low, Rounding_High);
      Native_Rounded : constant F32x4 := Backends.Native.Narrow_Round (Rounding_Low, Rounding_High);
      Negative_Rounded : constant F32x4 := Narrow_Round (Negative_Rounding_Low, Negative_Rounding_High);
      Native_Negative_Rounded : constant F32x4 := Backends.Native.Narrow_Round (Negative_Rounding_Low, Negative_Rounding_High);
      Subnormal : constant F32x4 := Narrow_Round (Subnormal_Low, Subnormal_High);
      Native_Subnormal : constant F32x4 := Backends.Native.Narrow_Round (Subnormal_Low, Subnormal_High);
      Positive_Overflow : constant F32x4 := Narrow_Round (Positive_Overflow_Low, Positive_Overflow_High);
      Native_Positive_Overflow : constant F32x4 := Backends.Native.Narrow_Round (Positive_Overflow_Low, Positive_Overflow_High);
      Negative_Overflow : constant F32x4 := Narrow_Round (Negative_Overflow_Low, Negative_Overflow_High);
      Native_Negative_Overflow : constant F32x4 := Backends.Native.Narrow_Round (Negative_Overflow_Low, Negative_Overflow_High);
      NaNs : constant F32x4 := Narrow_Round (NaN_Low, NaN_High);
      Native_NaNs : constant F32x4 := Backends.Native.Narrow_Round (NaN_Low, NaN_High);
      Expected_Exact : constant Lane_Values_F32x4 :=
        [F32_Of_Bits (16#0000_0000#), F32_Of_Bits (16#8000_0000#), F32_Of_Bits (16#7F80_0000#), F32_Of_Bits (16#FF80_0000#)];
      Expected_Rounded : constant Lane_Values_F32x4 :=
        [F32_Of_Bits (16#3F80_0000#), F32_Of_Bits (16#3F80_0001#), F32_Of_Bits (16#7F7F_FFFF#), F32_Of_Bits (16#7F80_0000#)];
      Expected_Negative_Rounded : constant Lane_Values_F32x4 :=
        [F32_Of_Bits (16#BF80_0000#), F32_Of_Bits (16#BF80_0002#), F32_Of_Bits (16#FF7F_FFFF#), F32_Of_Bits (16#FF80_0000#)];
      Expected_Subnormal : constant Lane_Values_F32x4 :=
        [F32_Of_Bits (16#0000_0000#), F32_Of_Bits (16#0000_0001#), F32_Of_Bits (16#8000_0000#), F32_Of_Bits (16#8000_0001#)];
      Expected_Positive_Overflow : constant Lane_Values_F32x4 :=
        [F32_Of_Bits (16#7F7F_FFFF#), F32_Of_Bits (16#7F80_0000#), F32_Of_Bits (16#7F80_0000#), F32_Of_Bits (16#7F7F_FFFF#)];
      Expected_Negative_Overflow : constant Lane_Values_F32x4 :=
        [F32_Of_Bits (16#FF7F_FFFF#), F32_Of_Bits (16#FF80_0000#), F32_Of_Bits (16#FF80_0000#), F32_Of_Bits (16#FF7F_FFFF#)];
   begin
      for Lane in Lane_Index_32x4 loop
         Check (Same (Extract (Exact, Lane), Expected_Exact (Lane)) and then Same (Extract (Native_Exact, Lane), Expected_Exact (Lane)), "F64 narrowing zero/infinity edge");
         Check (Same (Extract (Rounded, Lane), Expected_Rounded (Lane)) and then Same (Extract (Native_Rounded, Lane), Expected_Rounded (Lane)), "F64 narrowing rounded edge");
         Check (Same (Extract (Negative_Rounded, Lane), Expected_Negative_Rounded (Lane)) and then Same (Extract (Native_Negative_Rounded, Lane), Expected_Negative_Rounded (Lane)), "F64 narrowing negative rounded edge");
         Check (Same (Extract (Subnormal, Lane), Expected_Subnormal (Lane)) and then Same (Extract (Native_Subnormal, Lane), Expected_Subnormal (Lane)), "F64 narrowing subnormal edge");
         Check (Same (Extract (Positive_Overflow, Lane), Expected_Positive_Overflow (Lane)) and then Same (Extract (Native_Positive_Overflow, Lane), Expected_Positive_Overflow (Lane)), "F64 narrowing positive overflow boundary");
         Check (Same (Extract (Negative_Overflow, Lane), Expected_Negative_Overflow (Lane)) and then Same (Extract (Native_Negative_Overflow, Lane), Expected_Negative_Overflow (Lane)), "F64 narrowing negative overflow boundary");
         Check (Is_NaN (Extract (NaNs, Lane)) and then Is_NaN (Extract (Native_NaNs, Lane)), "F64 narrowing NaN edge");
      end loop;
   end Test_F64_Narrow_Edges;


begin
   Put_Line ("conversion differential tests seed=0xC0457A5712800A11");
   Test_F32_Widen_Edges;
   Test_F64_Narrow_Edges;
      declare
         Low : constant U16x8 := From_Lanes ([0, U16 (U8'Last), U16 (U8'Last) + 1, U16'Last, 0, U16 (U8'Last), U16 (U8'Last) + 1, U16'Last]);
         High : constant U16x8 := From_Lanes ([0, U16 (U8'Last), U16 (U8'Last) + 1, U16'Last, 0, U16 (U8'Last), U16 (U8'Last) + 1, U16'Last]);
         Scalar_Result : constant U8x16 := Narrow_Truncate (Low, High);
         Native_Result : constant U8x16 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_U16x8_To_U8x16 (Extract (Low, Lane)), "scalar Narrow_Truncate U16x8 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_U16x8_To_U8x16 (Extract (Low, Lane)), "native Narrow_Truncate U16x8 low lane");
            Check (Extract (Scalar_Result, Lane + 8) = Oracle_Narrow_Truncate_U16x8_To_U8x16 (Extract (High, Lane)), "scalar Narrow_Truncate U16x8 high lane");
            Check (Extract (Native_Result, Lane + 8) = Oracle_Narrow_Truncate_U16x8_To_U8x16 (Extract (High, Lane)), "native Narrow_Truncate U16x8 high lane");
         end loop;
      end;
      declare
         Low : constant U16x8 := From_Lanes ([0, U16 (U8'Last), U16 (U8'Last) + 1, U16'Last, 0, U16 (U8'Last), U16 (U8'Last) + 1, U16'Last]);
         High : constant U16x8 := From_Lanes ([0, U16 (U8'Last), U16 (U8'Last) + 1, U16'Last, 0, U16 (U8'Last), U16 (U8'Last) + 1, U16'Last]);
         Scalar_Result : constant U8x16 := Narrow_Saturate (Low, High);
         Native_Result : constant U8x16 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_U16x8_To_U8x16 (Extract (Low, Lane)), "scalar Narrow_Saturate U16x8 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_U16x8_To_U8x16 (Extract (Low, Lane)), "native Narrow_Saturate U16x8 low lane");
            Check (Extract (Scalar_Result, Lane + 8) = Oracle_Narrow_Saturate_U16x8_To_U8x16 (Extract (High, Lane)), "scalar Narrow_Saturate U16x8 high lane");
            Check (Extract (Native_Result, Lane + 8) = Oracle_Narrow_Saturate_U16x8_To_U8x16 (Extract (High, Lane)), "native Narrow_Saturate U16x8 high lane");
         end loop;
      end;
      declare
         Low : constant I16x8 := From_Lanes ([I16 (I8'First) - 1, I16 (I8'First), I16 (I8'Last), I16 (I8'Last) + 1, -1, 0, I16'First, I16'Last]);
         High : constant I16x8 := From_Lanes ([I16 (I8'First) - 1, I16 (I8'First), I16 (I8'Last), I16 (I8'Last) + 1, -1, 0, I16'First, I16'Last]);
         Scalar_Result : constant I8x16 := Narrow_Truncate (Low, High);
         Native_Result : constant I8x16 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_I16x8_To_I8x16 (Extract (Low, Lane)), "scalar Narrow_Truncate I16x8 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_I16x8_To_I8x16 (Extract (Low, Lane)), "native Narrow_Truncate I16x8 low lane");
            Check (Extract (Scalar_Result, Lane + 8) = Oracle_Narrow_Truncate_I16x8_To_I8x16 (Extract (High, Lane)), "scalar Narrow_Truncate I16x8 high lane");
            Check (Extract (Native_Result, Lane + 8) = Oracle_Narrow_Truncate_I16x8_To_I8x16 (Extract (High, Lane)), "native Narrow_Truncate I16x8 high lane");
         end loop;
      end;
      declare
         Low : constant I16x8 := From_Lanes ([I16 (I8'First) - 1, I16 (I8'First), I16 (I8'Last), I16 (I8'Last) + 1, -1, 0, I16'First, I16'Last]);
         High : constant I16x8 := From_Lanes ([I16 (I8'First) - 1, I16 (I8'First), I16 (I8'Last), I16 (I8'Last) + 1, -1, 0, I16'First, I16'Last]);
         Scalar_Result : constant I8x16 := Narrow_Saturate (Low, High);
         Native_Result : constant I8x16 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I16x8_To_I8x16 (Extract (Low, Lane)), "scalar Narrow_Saturate I16x8 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I16x8_To_I8x16 (Extract (Low, Lane)), "native Narrow_Saturate I16x8 low lane");
            Check (Extract (Scalar_Result, Lane + 8) = Oracle_Narrow_Saturate_I16x8_To_I8x16 (Extract (High, Lane)), "scalar Narrow_Saturate I16x8 high lane");
            Check (Extract (Native_Result, Lane + 8) = Oracle_Narrow_Saturate_I16x8_To_I8x16 (Extract (High, Lane)), "native Narrow_Saturate I16x8 high lane");
         end loop;
      end;
      declare
         Low : constant U32x4 := From_Lanes ([0, U32 (U16'Last), U32 (U16'Last) + 1, U32'Last]);
         High : constant U32x4 := From_Lanes ([0, U32 (U16'Last), U32 (U16'Last) + 1, U32'Last]);
         Scalar_Result : constant U16x8 := Narrow_Truncate (Low, High);
         Native_Result : constant U16x8 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_U32x4_To_U16x8 (Extract (Low, Lane)), "scalar Narrow_Truncate U32x4 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_U32x4_To_U16x8 (Extract (Low, Lane)), "native Narrow_Truncate U32x4 low lane");
            Check (Extract (Scalar_Result, Lane + 4) = Oracle_Narrow_Truncate_U32x4_To_U16x8 (Extract (High, Lane)), "scalar Narrow_Truncate U32x4 high lane");
            Check (Extract (Native_Result, Lane + 4) = Oracle_Narrow_Truncate_U32x4_To_U16x8 (Extract (High, Lane)), "native Narrow_Truncate U32x4 high lane");
         end loop;
      end;
      declare
         Low : constant U32x4 := From_Lanes ([0, U32 (U16'Last), U32 (U16'Last) + 1, U32'Last]);
         High : constant U32x4 := From_Lanes ([0, U32 (U16'Last), U32 (U16'Last) + 1, U32'Last]);
         Scalar_Result : constant U16x8 := Narrow_Saturate (Low, High);
         Native_Result : constant U16x8 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_U32x4_To_U16x8 (Extract (Low, Lane)), "scalar Narrow_Saturate U32x4 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_U32x4_To_U16x8 (Extract (Low, Lane)), "native Narrow_Saturate U32x4 low lane");
            Check (Extract (Scalar_Result, Lane + 4) = Oracle_Narrow_Saturate_U32x4_To_U16x8 (Extract (High, Lane)), "scalar Narrow_Saturate U32x4 high lane");
            Check (Extract (Native_Result, Lane + 4) = Oracle_Narrow_Saturate_U32x4_To_U16x8 (Extract (High, Lane)), "native Narrow_Saturate U32x4 high lane");
         end loop;
      end;
      declare
         Low : constant I32x4 := From_Lanes ([I32 (I16'First) - 1, I32 (I16'First), I32 (I16'Last), I32 (I16'Last) + 1]);
         High : constant I32x4 := From_Lanes ([-1, 0, I32'First, I32'Last]);
         Scalar_Result : constant I16x8 := Narrow_Truncate (Low, High);
         Native_Result : constant I16x8 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_I32x4_To_I16x8 (Extract (Low, Lane)), "scalar Narrow_Truncate I32x4 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_I32x4_To_I16x8 (Extract (Low, Lane)), "native Narrow_Truncate I32x4 low lane");
            Check (Extract (Scalar_Result, Lane + 4) = Oracle_Narrow_Truncate_I32x4_To_I16x8 (Extract (High, Lane)), "scalar Narrow_Truncate I32x4 high lane");
            Check (Extract (Native_Result, Lane + 4) = Oracle_Narrow_Truncate_I32x4_To_I16x8 (Extract (High, Lane)), "native Narrow_Truncate I32x4 high lane");
         end loop;
      end;
      declare
         Low : constant I32x4 := From_Lanes ([I32 (I16'First) - 1, I32 (I16'First), I32 (I16'Last), I32 (I16'Last) + 1]);
         High : constant I32x4 := From_Lanes ([-1, 0, I32'First, I32'Last]);
         Scalar_Result : constant I16x8 := Narrow_Saturate (Low, High);
         Native_Result : constant I16x8 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I32x4_To_I16x8 (Extract (Low, Lane)), "scalar Narrow_Saturate I32x4 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I32x4_To_I16x8 (Extract (Low, Lane)), "native Narrow_Saturate I32x4 low lane");
            Check (Extract (Scalar_Result, Lane + 4) = Oracle_Narrow_Saturate_I32x4_To_I16x8 (Extract (High, Lane)), "scalar Narrow_Saturate I32x4 high lane");
            Check (Extract (Native_Result, Lane + 4) = Oracle_Narrow_Saturate_I32x4_To_I16x8 (Extract (High, Lane)), "native Narrow_Saturate I32x4 high lane");
         end loop;
      end;
      declare
         Low : constant U64x2 := From_Lanes ([0, U64 (U32'Last)]);
         High : constant U64x2 := From_Lanes ([U64 (U32'Last) + 1, U64'Last]);
         Scalar_Result : constant U32x4 := Narrow_Truncate (Low, High);
         Native_Result : constant U32x4 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_U64x2_To_U32x4 (Extract (Low, Lane)), "scalar Narrow_Truncate U64x2 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_U64x2_To_U32x4 (Extract (Low, Lane)), "native Narrow_Truncate U64x2 low lane");
            Check (Extract (Scalar_Result, Lane + 2) = Oracle_Narrow_Truncate_U64x2_To_U32x4 (Extract (High, Lane)), "scalar Narrow_Truncate U64x2 high lane");
            Check (Extract (Native_Result, Lane + 2) = Oracle_Narrow_Truncate_U64x2_To_U32x4 (Extract (High, Lane)), "native Narrow_Truncate U64x2 high lane");
         end loop;
      end;
      declare
         Low : constant U64x2 := From_Lanes ([0, U64 (U32'Last)]);
         High : constant U64x2 := From_Lanes ([U64 (U32'Last) + 1, U64'Last]);
         Scalar_Result : constant U32x4 := Narrow_Saturate (Low, High);
         Native_Result : constant U32x4 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_U64x2_To_U32x4 (Extract (Low, Lane)), "scalar Narrow_Saturate U64x2 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_U64x2_To_U32x4 (Extract (Low, Lane)), "native Narrow_Saturate U64x2 low lane");
            Check (Extract (Scalar_Result, Lane + 2) = Oracle_Narrow_Saturate_U64x2_To_U32x4 (Extract (High, Lane)), "scalar Narrow_Saturate U64x2 high lane");
            Check (Extract (Native_Result, Lane + 2) = Oracle_Narrow_Saturate_U64x2_To_U32x4 (Extract (High, Lane)), "native Narrow_Saturate U64x2 high lane");
         end loop;
      end;
      declare
         Low : constant I64x2 := From_Lanes ([I64 (I32'First) - 1, I64 (I32'First)]);
         High : constant I64x2 := From_Lanes ([I64 (I32'Last), I64 (I32'Last) + 1]);
         Scalar_Result : constant I32x4 := Narrow_Truncate (Low, High);
         Native_Result : constant I32x4 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_I64x2_To_I32x4 (Extract (Low, Lane)), "scalar Narrow_Truncate I64x2 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_I64x2_To_I32x4 (Extract (Low, Lane)), "native Narrow_Truncate I64x2 low lane");
            Check (Extract (Scalar_Result, Lane + 2) = Oracle_Narrow_Truncate_I64x2_To_I32x4 (Extract (High, Lane)), "scalar Narrow_Truncate I64x2 high lane");
            Check (Extract (Native_Result, Lane + 2) = Oracle_Narrow_Truncate_I64x2_To_I32x4 (Extract (High, Lane)), "native Narrow_Truncate I64x2 high lane");
         end loop;
      end;
      declare
         Low : constant I64x2 := From_Lanes ([I64 (I32'First) - 1, I64 (I32'First)]);
         High : constant I64x2 := From_Lanes ([I64 (I32'Last), I64 (I32'Last) + 1]);
         Scalar_Result : constant I32x4 := Narrow_Saturate (Low, High);
         Native_Result : constant I32x4 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I64x2_To_I32x4 (Extract (Low, Lane)), "scalar Narrow_Saturate I64x2 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I64x2_To_I32x4 (Extract (Low, Lane)), "native Narrow_Saturate I64x2 low lane");
            Check (Extract (Scalar_Result, Lane + 2) = Oracle_Narrow_Saturate_I64x2_To_I32x4 (Extract (High, Lane)), "scalar Narrow_Saturate I64x2 high lane");
            Check (Extract (Native_Result, Lane + 2) = Oracle_Narrow_Saturate_I64x2_To_I32x4 (Extract (High, Lane)), "native Narrow_Saturate I64x2 high lane");
         end loop;
      end;
      declare
         Low : constant I16x8 := From_Lanes ([-1, 0, I16 (U8'Last), I16 (U8'Last) + 1, I16'First, I16'Last, -1, 0]);
         High : constant I16x8 := From_Lanes ([I16 (U8'Last), I16 (U8'Last) + 1, I16'First, I16'Last, -1, 0, I16 (U8'Last), I16 (U8'Last) + 1]);
         Scalar_Result : constant U8x16 := Narrow_Saturate (Low, High);
         Native_Result : constant U8x16 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I16x8_To_U8x16 (Extract (Low, Lane)), "scalar Narrow_Saturate I16x8 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I16x8_To_U8x16 (Extract (Low, Lane)), "native Narrow_Saturate I16x8 low lane");
            Check (Extract (Scalar_Result, Lane + 8) = Oracle_Narrow_Saturate_I16x8_To_U8x16 (Extract (High, Lane)), "scalar Narrow_Saturate I16x8 high lane");
            Check (Extract (Native_Result, Lane + 8) = Oracle_Narrow_Saturate_I16x8_To_U8x16 (Extract (High, Lane)), "native Narrow_Saturate I16x8 high lane");
         end loop;
      end;
      declare
         Low : constant I32x4 := From_Lanes ([-1, 0, I32 (U16'Last), I32 (U16'Last) + 1]);
         High : constant I32x4 := From_Lanes ([I32'First, I32'Last, -1, 0]);
         Scalar_Result : constant U16x8 := Narrow_Saturate (Low, High);
         Native_Result : constant U16x8 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I32x4_To_U16x8 (Extract (Low, Lane)), "scalar Narrow_Saturate I32x4 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I32x4_To_U16x8 (Extract (Low, Lane)), "native Narrow_Saturate I32x4 low lane");
            Check (Extract (Scalar_Result, Lane + 4) = Oracle_Narrow_Saturate_I32x4_To_U16x8 (Extract (High, Lane)), "scalar Narrow_Saturate I32x4 high lane");
            Check (Extract (Native_Result, Lane + 4) = Oracle_Narrow_Saturate_I32x4_To_U16x8 (Extract (High, Lane)), "native Narrow_Saturate I32x4 high lane");
         end loop;
      end;
      declare
         Low : constant I64x2 := From_Lanes ([-1, 0]);
         High : constant I64x2 := From_Lanes ([I64 (U32'Last), I64 (U32'Last) + 1]);
         Scalar_Result : constant U32x4 := Narrow_Saturate (Low, High);
         Native_Result : constant U32x4 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I64x2_To_U32x4 (Extract (Low, Lane)), "scalar Narrow_Saturate I64x2 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I64x2_To_U32x4 (Extract (Low, Lane)), "native Narrow_Saturate I64x2 low lane");
            Check (Extract (Scalar_Result, Lane + 2) = Oracle_Narrow_Saturate_I64x2_To_U32x4 (Extract (High, Lane)), "scalar Narrow_Saturate I64x2 high lane");
            Check (Extract (Native_Result, Lane + 2) = Oracle_Narrow_Saturate_I64x2_To_U32x4 (Extract (High, Lane)), "native Narrow_Saturate I64x2 high lane");
         end loop;
      end;
   for Iteration in Positive range 1 .. 512 loop
      pragma Unreferenced (Iteration);
      declare
         Source : constant U8x16 := Random_U8x16;
         Scalar_Result : constant I8x16 := Bit_Cast (Source);
         Native_Result : constant I8x16 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_8x16 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_U8_To_I8 (Extract (Source, Lane))), "scalar U8x16 to I8x16 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_U8_To_I8 (Extract (Source, Lane))), "native U8x16 to I8x16 bit cast lane");
         end loop;
      end;
      declare
         Source : constant I8x16 := Random_I8x16;
         Scalar_Result : constant U8x16 := Bit_Cast (Source);
         Native_Result : constant U8x16 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_8x16 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_I8_To_U8 (Extract (Source, Lane))), "scalar I8x16 to U8x16 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_I8_To_U8 (Extract (Source, Lane))), "native I8x16 to U8x16 bit cast lane");
         end loop;
      end;
      declare
         Source : constant U16x8 := Random_U16x8;
         Scalar_Result : constant I16x8 := Bit_Cast (Source);
         Native_Result : constant I16x8 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_16x8 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_U16_To_I16 (Extract (Source, Lane))), "scalar U16x8 to I16x8 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_U16_To_I16 (Extract (Source, Lane))), "native U16x8 to I16x8 bit cast lane");
         end loop;
      end;
      declare
         Source : constant I16x8 := Random_I16x8;
         Scalar_Result : constant U16x8 := Bit_Cast (Source);
         Native_Result : constant U16x8 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_16x8 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_I16_To_U16 (Extract (Source, Lane))), "scalar I16x8 to U16x8 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_I16_To_U16 (Extract (Source, Lane))), "native I16x8 to U16x8 bit cast lane");
         end loop;
      end;
      declare
         Source : constant U32x4 := Random_U32x4;
         Scalar_Result : constant I32x4 := Bit_Cast (Source);
         Native_Result : constant I32x4 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_32x4 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_U32_To_I32 (Extract (Source, Lane))), "scalar U32x4 to I32x4 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_U32_To_I32 (Extract (Source, Lane))), "native U32x4 to I32x4 bit cast lane");
         end loop;
      end;
      declare
         Source : constant U32x4 := Random_U32x4;
         Scalar_Result : constant F32x4 := Bit_Cast (Source);
         Native_Result : constant F32x4 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_32x4 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_U32_To_F32 (Extract (Source, Lane))), "scalar U32x4 to F32x4 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_U32_To_F32 (Extract (Source, Lane))), "native U32x4 to F32x4 bit cast lane");
         end loop;
      end;
      declare
         Source : constant I32x4 := Random_I32x4;
         Scalar_Result : constant U32x4 := Bit_Cast (Source);
         Native_Result : constant U32x4 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_32x4 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_I32_To_U32 (Extract (Source, Lane))), "scalar I32x4 to U32x4 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_I32_To_U32 (Extract (Source, Lane))), "native I32x4 to U32x4 bit cast lane");
         end loop;
      end;
      declare
         Source : constant I32x4 := Random_I32x4;
         Scalar_Result : constant F32x4 := Bit_Cast (Source);
         Native_Result : constant F32x4 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_32x4 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_I32_To_F32 (Extract (Source, Lane))), "scalar I32x4 to F32x4 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_I32_To_F32 (Extract (Source, Lane))), "native I32x4 to F32x4 bit cast lane");
         end loop;
      end;
      declare
         Source : constant F32x4 := Random_F32x4;
         Scalar_Result : constant U32x4 := Bit_Cast (Source);
         Native_Result : constant U32x4 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_32x4 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_F32_To_U32 (Extract (Source, Lane))), "scalar F32x4 to U32x4 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_F32_To_U32 (Extract (Source, Lane))), "native F32x4 to U32x4 bit cast lane");
         end loop;
      end;
      declare
         Source : constant F32x4 := Random_F32x4;
         Scalar_Result : constant I32x4 := Bit_Cast (Source);
         Native_Result : constant I32x4 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_32x4 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_F32_To_I32 (Extract (Source, Lane))), "scalar F32x4 to I32x4 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_F32_To_I32 (Extract (Source, Lane))), "native F32x4 to I32x4 bit cast lane");
         end loop;
      end;
      declare
         Source : constant U64x2 := Random_U64x2;
         Scalar_Result : constant I64x2 := Bit_Cast (Source);
         Native_Result : constant I64x2 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_64x2 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_U64_To_I64 (Extract (Source, Lane))), "scalar U64x2 to I64x2 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_U64_To_I64 (Extract (Source, Lane))), "native U64x2 to I64x2 bit cast lane");
         end loop;
      end;
      declare
         Source : constant U64x2 := Random_U64x2;
         Scalar_Result : constant F64x2 := Bit_Cast (Source);
         Native_Result : constant F64x2 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_64x2 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_U64_To_F64 (Extract (Source, Lane))), "scalar U64x2 to F64x2 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_U64_To_F64 (Extract (Source, Lane))), "native U64x2 to F64x2 bit cast lane");
         end loop;
      end;
      declare
         Source : constant I64x2 := Random_I64x2;
         Scalar_Result : constant U64x2 := Bit_Cast (Source);
         Native_Result : constant U64x2 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_64x2 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_I64_To_U64 (Extract (Source, Lane))), "scalar I64x2 to U64x2 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_I64_To_U64 (Extract (Source, Lane))), "native I64x2 to U64x2 bit cast lane");
         end loop;
      end;
      declare
         Source : constant I64x2 := Random_I64x2;
         Scalar_Result : constant F64x2 := Bit_Cast (Source);
         Native_Result : constant F64x2 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_64x2 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_I64_To_F64 (Extract (Source, Lane))), "scalar I64x2 to F64x2 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_I64_To_F64 (Extract (Source, Lane))), "native I64x2 to F64x2 bit cast lane");
         end loop;
      end;
      declare
         Source : constant F64x2 := Random_F64x2;
         Scalar_Result : constant U64x2 := Bit_Cast (Source);
         Native_Result : constant U64x2 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_64x2 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_F64_To_U64 (Extract (Source, Lane))), "scalar F64x2 to U64x2 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_F64_To_U64 (Extract (Source, Lane))), "native F64x2 to U64x2 bit cast lane");
         end loop;
      end;
      declare
         Source : constant F64x2 := Random_F64x2;
         Scalar_Result : constant I64x2 := Bit_Cast (Source);
         Native_Result : constant I64x2 := Backends.Native.Bit_Cast (Source);
      begin
         for Lane in Lane_Index_64x2 loop
            Check (Same (Extract (Scalar_Result, Lane), Cast_F64_To_I64 (Extract (Source, Lane))), "scalar F64x2 to I64x2 bit cast lane");
            Check (Same (Extract (Native_Result, Lane), Cast_F64_To_I64 (Extract (Source, Lane))), "native F64x2 to I64x2 bit cast lane");
         end loop;
      end;
      declare
         Source : constant U8x16 := Random_U8x16;
         Scalar_Low : constant U16x8 := Widen_Low (Source);
         Scalar_High : constant U16x8 := Widen_High (Source);
         Native_Low : constant U16x8 := Backends.Native.Widen_Low (Source);
         Native_High : constant U16x8 := Backends.Native.Widen_High (Source);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Low, Lane) = U16 (Extract (Source, Lane)), "scalar U8x16 low widening lane");
            Check (Extract (Native_Low, Lane) = U16 (Extract (Source, Lane)), "native U8x16 low widening lane");
            Check (Extract (Scalar_High, Lane) = U16 (Extract (Source, Lane + 8)), "scalar U8x16 high widening lane");
            Check (Extract (Native_High, Lane) = U16 (Extract (Source, Lane + 8)), "native U8x16 high widening lane");
         end loop;
      end;
      declare
         Source : constant I8x16 := Random_I8x16;
         Scalar_Low : constant I16x8 := Widen_Low (Source);
         Scalar_High : constant I16x8 := Widen_High (Source);
         Native_Low : constant I16x8 := Backends.Native.Widen_Low (Source);
         Native_High : constant I16x8 := Backends.Native.Widen_High (Source);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Low, Lane) = I16 (Extract (Source, Lane)), "scalar I8x16 low widening lane");
            Check (Extract (Native_Low, Lane) = I16 (Extract (Source, Lane)), "native I8x16 low widening lane");
            Check (Extract (Scalar_High, Lane) = I16 (Extract (Source, Lane + 8)), "scalar I8x16 high widening lane");
            Check (Extract (Native_High, Lane) = I16 (Extract (Source, Lane + 8)), "native I8x16 high widening lane");
         end loop;
      end;
      declare
         Source : constant U16x8 := Random_U16x8;
         Scalar_Low : constant U32x4 := Widen_Low (Source);
         Scalar_High : constant U32x4 := Widen_High (Source);
         Native_Low : constant U32x4 := Backends.Native.Widen_Low (Source);
         Native_High : constant U32x4 := Backends.Native.Widen_High (Source);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Low, Lane) = U32 (Extract (Source, Lane)), "scalar U16x8 low widening lane");
            Check (Extract (Native_Low, Lane) = U32 (Extract (Source, Lane)), "native U16x8 low widening lane");
            Check (Extract (Scalar_High, Lane) = U32 (Extract (Source, Lane + 4)), "scalar U16x8 high widening lane");
            Check (Extract (Native_High, Lane) = U32 (Extract (Source, Lane + 4)), "native U16x8 high widening lane");
         end loop;
      end;
      declare
         Source : constant I16x8 := Random_I16x8;
         Scalar_Low : constant I32x4 := Widen_Low (Source);
         Scalar_High : constant I32x4 := Widen_High (Source);
         Native_Low : constant I32x4 := Backends.Native.Widen_Low (Source);
         Native_High : constant I32x4 := Backends.Native.Widen_High (Source);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Low, Lane) = I32 (Extract (Source, Lane)), "scalar I16x8 low widening lane");
            Check (Extract (Native_Low, Lane) = I32 (Extract (Source, Lane)), "native I16x8 low widening lane");
            Check (Extract (Scalar_High, Lane) = I32 (Extract (Source, Lane + 4)), "scalar I16x8 high widening lane");
            Check (Extract (Native_High, Lane) = I32 (Extract (Source, Lane + 4)), "native I16x8 high widening lane");
         end loop;
      end;
      declare
         Source : constant U32x4 := Random_U32x4;
         Scalar_Low : constant U64x2 := Widen_Low (Source);
         Scalar_High : constant U64x2 := Widen_High (Source);
         Native_Low : constant U64x2 := Backends.Native.Widen_Low (Source);
         Native_High : constant U64x2 := Backends.Native.Widen_High (Source);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Low, Lane) = U64 (Extract (Source, Lane)), "scalar U32x4 low widening lane");
            Check (Extract (Native_Low, Lane) = U64 (Extract (Source, Lane)), "native U32x4 low widening lane");
            Check (Extract (Scalar_High, Lane) = U64 (Extract (Source, Lane + 2)), "scalar U32x4 high widening lane");
            Check (Extract (Native_High, Lane) = U64 (Extract (Source, Lane + 2)), "native U32x4 high widening lane");
         end loop;
      end;
      declare
         Source : constant I32x4 := Random_I32x4;
         Scalar_Low : constant I64x2 := Widen_Low (Source);
         Scalar_High : constant I64x2 := Widen_High (Source);
         Native_Low : constant I64x2 := Backends.Native.Widen_Low (Source);
         Native_High : constant I64x2 := Backends.Native.Widen_High (Source);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Low, Lane) = I64 (Extract (Source, Lane)), "scalar I32x4 low widening lane");
            Check (Extract (Native_Low, Lane) = I64 (Extract (Source, Lane)), "native I32x4 low widening lane");
            Check (Extract (Scalar_High, Lane) = I64 (Extract (Source, Lane + 2)), "scalar I32x4 high widening lane");
            Check (Extract (Native_High, Lane) = I64 (Extract (Source, Lane + 2)), "native I32x4 high widening lane");
         end loop;
      end;
      declare
         Source : constant F32x4 := Random_F32x4;
         Scalar_Low : constant F64x2 := Widen_Low (Source);
         Scalar_High : constant F64x2 := Widen_High (Source);
         Native_Low : constant F64x2 := Backends.Native.Widen_Low (Source);
         Native_High : constant F64x2 := Backends.Native.Widen_High (Source);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Low, Lane) = F64 (Extract (Source, Lane)), "scalar F32x4 low widening lane");
            Check (Extract (Native_Low, Lane) = F64 (Extract (Source, Lane)), "native F32x4 low widening lane");
            Check (Extract (Scalar_High, Lane) = F64 (Extract (Source, Lane + 2)), "scalar F32x4 high widening lane");
            Check (Extract (Native_High, Lane) = F64 (Extract (Source, Lane + 2)), "native F32x4 high widening lane");
         end loop;
      end;
      declare
         Low : constant U16x8 := Random_U16x8;
         High : constant U16x8 := Random_U16x8;
         Scalar_Result : constant U8x16 := Narrow_Truncate (Low, High);
         Native_Result : constant U8x16 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_U16x8_To_U8x16 (Extract (Low, Lane)), "scalar Narrow_Truncate U16x8 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_U16x8_To_U8x16 (Extract (Low, Lane)), "native Narrow_Truncate U16x8 low lane");
            Check (Extract (Scalar_Result, Lane + 8) = Oracle_Narrow_Truncate_U16x8_To_U8x16 (Extract (High, Lane)), "scalar Narrow_Truncate U16x8 high lane");
            Check (Extract (Native_Result, Lane + 8) = Oracle_Narrow_Truncate_U16x8_To_U8x16 (Extract (High, Lane)), "native Narrow_Truncate U16x8 high lane");
         end loop;
      end;
      declare
         Low : constant U16x8 := Random_U16x8;
         High : constant U16x8 := Random_U16x8;
         Scalar_Result : constant U8x16 := Narrow_Saturate (Low, High);
         Native_Result : constant U8x16 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_U16x8_To_U8x16 (Extract (Low, Lane)), "scalar Narrow_Saturate U16x8 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_U16x8_To_U8x16 (Extract (Low, Lane)), "native Narrow_Saturate U16x8 low lane");
            Check (Extract (Scalar_Result, Lane + 8) = Oracle_Narrow_Saturate_U16x8_To_U8x16 (Extract (High, Lane)), "scalar Narrow_Saturate U16x8 high lane");
            Check (Extract (Native_Result, Lane + 8) = Oracle_Narrow_Saturate_U16x8_To_U8x16 (Extract (High, Lane)), "native Narrow_Saturate U16x8 high lane");
         end loop;
      end;
      declare
         Low : constant I16x8 := Random_I16x8;
         High : constant I16x8 := Random_I16x8;
         Scalar_Result : constant I8x16 := Narrow_Truncate (Low, High);
         Native_Result : constant I8x16 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_I16x8_To_I8x16 (Extract (Low, Lane)), "scalar Narrow_Truncate I16x8 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_I16x8_To_I8x16 (Extract (Low, Lane)), "native Narrow_Truncate I16x8 low lane");
            Check (Extract (Scalar_Result, Lane + 8) = Oracle_Narrow_Truncate_I16x8_To_I8x16 (Extract (High, Lane)), "scalar Narrow_Truncate I16x8 high lane");
            Check (Extract (Native_Result, Lane + 8) = Oracle_Narrow_Truncate_I16x8_To_I8x16 (Extract (High, Lane)), "native Narrow_Truncate I16x8 high lane");
         end loop;
      end;
      declare
         Low : constant I16x8 := Random_I16x8;
         High : constant I16x8 := Random_I16x8;
         Scalar_Result : constant I8x16 := Narrow_Saturate (Low, High);
         Native_Result : constant I8x16 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I16x8_To_I8x16 (Extract (Low, Lane)), "scalar Narrow_Saturate I16x8 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I16x8_To_I8x16 (Extract (Low, Lane)), "native Narrow_Saturate I16x8 low lane");
            Check (Extract (Scalar_Result, Lane + 8) = Oracle_Narrow_Saturate_I16x8_To_I8x16 (Extract (High, Lane)), "scalar Narrow_Saturate I16x8 high lane");
            Check (Extract (Native_Result, Lane + 8) = Oracle_Narrow_Saturate_I16x8_To_I8x16 (Extract (High, Lane)), "native Narrow_Saturate I16x8 high lane");
         end loop;
      end;
      declare
         Low : constant U32x4 := Random_U32x4;
         High : constant U32x4 := Random_U32x4;
         Scalar_Result : constant U16x8 := Narrow_Truncate (Low, High);
         Native_Result : constant U16x8 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_U32x4_To_U16x8 (Extract (Low, Lane)), "scalar Narrow_Truncate U32x4 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_U32x4_To_U16x8 (Extract (Low, Lane)), "native Narrow_Truncate U32x4 low lane");
            Check (Extract (Scalar_Result, Lane + 4) = Oracle_Narrow_Truncate_U32x4_To_U16x8 (Extract (High, Lane)), "scalar Narrow_Truncate U32x4 high lane");
            Check (Extract (Native_Result, Lane + 4) = Oracle_Narrow_Truncate_U32x4_To_U16x8 (Extract (High, Lane)), "native Narrow_Truncate U32x4 high lane");
         end loop;
      end;
      declare
         Low : constant U32x4 := Random_U32x4;
         High : constant U32x4 := Random_U32x4;
         Scalar_Result : constant U16x8 := Narrow_Saturate (Low, High);
         Native_Result : constant U16x8 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_U32x4_To_U16x8 (Extract (Low, Lane)), "scalar Narrow_Saturate U32x4 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_U32x4_To_U16x8 (Extract (Low, Lane)), "native Narrow_Saturate U32x4 low lane");
            Check (Extract (Scalar_Result, Lane + 4) = Oracle_Narrow_Saturate_U32x4_To_U16x8 (Extract (High, Lane)), "scalar Narrow_Saturate U32x4 high lane");
            Check (Extract (Native_Result, Lane + 4) = Oracle_Narrow_Saturate_U32x4_To_U16x8 (Extract (High, Lane)), "native Narrow_Saturate U32x4 high lane");
         end loop;
      end;
      declare
         Low : constant I32x4 := Random_I32x4;
         High : constant I32x4 := Random_I32x4;
         Scalar_Result : constant I16x8 := Narrow_Truncate (Low, High);
         Native_Result : constant I16x8 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_I32x4_To_I16x8 (Extract (Low, Lane)), "scalar Narrow_Truncate I32x4 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_I32x4_To_I16x8 (Extract (Low, Lane)), "native Narrow_Truncate I32x4 low lane");
            Check (Extract (Scalar_Result, Lane + 4) = Oracle_Narrow_Truncate_I32x4_To_I16x8 (Extract (High, Lane)), "scalar Narrow_Truncate I32x4 high lane");
            Check (Extract (Native_Result, Lane + 4) = Oracle_Narrow_Truncate_I32x4_To_I16x8 (Extract (High, Lane)), "native Narrow_Truncate I32x4 high lane");
         end loop;
      end;
      declare
         Low : constant I32x4 := Random_I32x4;
         High : constant I32x4 := Random_I32x4;
         Scalar_Result : constant I16x8 := Narrow_Saturate (Low, High);
         Native_Result : constant I16x8 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I32x4_To_I16x8 (Extract (Low, Lane)), "scalar Narrow_Saturate I32x4 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I32x4_To_I16x8 (Extract (Low, Lane)), "native Narrow_Saturate I32x4 low lane");
            Check (Extract (Scalar_Result, Lane + 4) = Oracle_Narrow_Saturate_I32x4_To_I16x8 (Extract (High, Lane)), "scalar Narrow_Saturate I32x4 high lane");
            Check (Extract (Native_Result, Lane + 4) = Oracle_Narrow_Saturate_I32x4_To_I16x8 (Extract (High, Lane)), "native Narrow_Saturate I32x4 high lane");
         end loop;
      end;
      declare
         Low : constant U64x2 := Random_U64x2;
         High : constant U64x2 := Random_U64x2;
         Scalar_Result : constant U32x4 := Narrow_Truncate (Low, High);
         Native_Result : constant U32x4 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_U64x2_To_U32x4 (Extract (Low, Lane)), "scalar Narrow_Truncate U64x2 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_U64x2_To_U32x4 (Extract (Low, Lane)), "native Narrow_Truncate U64x2 low lane");
            Check (Extract (Scalar_Result, Lane + 2) = Oracle_Narrow_Truncate_U64x2_To_U32x4 (Extract (High, Lane)), "scalar Narrow_Truncate U64x2 high lane");
            Check (Extract (Native_Result, Lane + 2) = Oracle_Narrow_Truncate_U64x2_To_U32x4 (Extract (High, Lane)), "native Narrow_Truncate U64x2 high lane");
         end loop;
      end;
      declare
         Low : constant U64x2 := Random_U64x2;
         High : constant U64x2 := Random_U64x2;
         Scalar_Result : constant U32x4 := Narrow_Saturate (Low, High);
         Native_Result : constant U32x4 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_U64x2_To_U32x4 (Extract (Low, Lane)), "scalar Narrow_Saturate U64x2 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_U64x2_To_U32x4 (Extract (Low, Lane)), "native Narrow_Saturate U64x2 low lane");
            Check (Extract (Scalar_Result, Lane + 2) = Oracle_Narrow_Saturate_U64x2_To_U32x4 (Extract (High, Lane)), "scalar Narrow_Saturate U64x2 high lane");
            Check (Extract (Native_Result, Lane + 2) = Oracle_Narrow_Saturate_U64x2_To_U32x4 (Extract (High, Lane)), "native Narrow_Saturate U64x2 high lane");
         end loop;
      end;
      declare
         Low : constant I64x2 := Random_I64x2;
         High : constant I64x2 := Random_I64x2;
         Scalar_Result : constant I32x4 := Narrow_Truncate (Low, High);
         Native_Result : constant I32x4 := Backends.Native.Narrow_Truncate (Low, High);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Truncate_I64x2_To_I32x4 (Extract (Low, Lane)), "scalar Narrow_Truncate I64x2 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Truncate_I64x2_To_I32x4 (Extract (Low, Lane)), "native Narrow_Truncate I64x2 low lane");
            Check (Extract (Scalar_Result, Lane + 2) = Oracle_Narrow_Truncate_I64x2_To_I32x4 (Extract (High, Lane)), "scalar Narrow_Truncate I64x2 high lane");
            Check (Extract (Native_Result, Lane + 2) = Oracle_Narrow_Truncate_I64x2_To_I32x4 (Extract (High, Lane)), "native Narrow_Truncate I64x2 high lane");
         end loop;
      end;
      declare
         Low : constant I64x2 := Random_I64x2;
         High : constant I64x2 := Random_I64x2;
         Scalar_Result : constant I32x4 := Narrow_Saturate (Low, High);
         Native_Result : constant I32x4 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I64x2_To_I32x4 (Extract (Low, Lane)), "scalar Narrow_Saturate I64x2 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I64x2_To_I32x4 (Extract (Low, Lane)), "native Narrow_Saturate I64x2 low lane");
            Check (Extract (Scalar_Result, Lane + 2) = Oracle_Narrow_Saturate_I64x2_To_I32x4 (Extract (High, Lane)), "scalar Narrow_Saturate I64x2 high lane");
            Check (Extract (Native_Result, Lane + 2) = Oracle_Narrow_Saturate_I64x2_To_I32x4 (Extract (High, Lane)), "native Narrow_Saturate I64x2 high lane");
         end loop;
      end;
      declare
         Low : constant I16x8 := Random_I16x8;
         High : constant I16x8 := Random_I16x8;
         Scalar_Result : constant U8x16 := Narrow_Saturate (Low, High);
         Native_Result : constant U8x16 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 7 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I16x8_To_U8x16 (Extract (Low, Lane)), "scalar Narrow_Saturate I16x8 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I16x8_To_U8x16 (Extract (Low, Lane)), "native Narrow_Saturate I16x8 low lane");
            Check (Extract (Scalar_Result, Lane + 8) = Oracle_Narrow_Saturate_I16x8_To_U8x16 (Extract (High, Lane)), "scalar Narrow_Saturate I16x8 high lane");
            Check (Extract (Native_Result, Lane + 8) = Oracle_Narrow_Saturate_I16x8_To_U8x16 (Extract (High, Lane)), "native Narrow_Saturate I16x8 high lane");
         end loop;
      end;
      declare
         Low : constant I32x4 := Random_I32x4;
         High : constant I32x4 := Random_I32x4;
         Scalar_Result : constant U16x8 := Narrow_Saturate (Low, High);
         Native_Result : constant U16x8 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 3 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I32x4_To_U16x8 (Extract (Low, Lane)), "scalar Narrow_Saturate I32x4 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I32x4_To_U16x8 (Extract (Low, Lane)), "native Narrow_Saturate I32x4 low lane");
            Check (Extract (Scalar_Result, Lane + 4) = Oracle_Narrow_Saturate_I32x4_To_U16x8 (Extract (High, Lane)), "scalar Narrow_Saturate I32x4 high lane");
            Check (Extract (Native_Result, Lane + 4) = Oracle_Narrow_Saturate_I32x4_To_U16x8 (Extract (High, Lane)), "native Narrow_Saturate I32x4 high lane");
         end loop;
      end;
      declare
         Low : constant I64x2 := Random_I64x2;
         High : constant I64x2 := Random_I64x2;
         Scalar_Result : constant U32x4 := Narrow_Saturate (Low, High);
         Native_Result : constant U32x4 := Backends.Native.Narrow_Saturate (Low, High);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Extract (Scalar_Result, Lane) = Oracle_Narrow_Saturate_I64x2_To_U32x4 (Extract (Low, Lane)), "scalar Narrow_Saturate I64x2 low lane");
            Check (Extract (Native_Result, Lane) = Oracle_Narrow_Saturate_I64x2_To_U32x4 (Extract (Low, Lane)), "native Narrow_Saturate I64x2 low lane");
            Check (Extract (Scalar_Result, Lane + 2) = Oracle_Narrow_Saturate_I64x2_To_U32x4 (Extract (High, Lane)), "scalar Narrow_Saturate I64x2 high lane");
            Check (Extract (Native_Result, Lane + 2) = Oracle_Narrow_Saturate_I64x2_To_U32x4 (Extract (High, Lane)), "native Narrow_Saturate I64x2 high lane");
         end loop;
      end;
      declare
         Low : constant F64x2 := Random_Narrow_F64x2;
         High : constant F64x2 := Random_Narrow_F64x2;
         Scalar_Result : constant F32x4 := Narrow_Round (Low, High);
         Native_Result : constant F32x4 := Backends.Native.Narrow_Round (Low, High);
      begin
         for Lane in Natural range 0 .. 1 loop
            Check (Same (Extract (Scalar_Result, Lane), Oracle_Narrow_Round_F64x2_To_F32x4 (Extract (Low, Lane))), "scalar Narrow_Round F64x2 low lane");
            Check (Same (Extract (Native_Result, Lane), Oracle_Narrow_Round_F64x2_To_F32x4 (Extract (Low, Lane))), "native Narrow_Round F64x2 low lane");
            Check (Same (Extract (Scalar_Result, Lane + 2), Oracle_Narrow_Round_F64x2_To_F32x4 (Extract (High, Lane))), "scalar Narrow_Round F64x2 high lane");
            Check (Same (Extract (Native_Result, Lane + 2), Oracle_Narrow_Round_F64x2_To_F32x4 (Extract (High, Lane))), "native Narrow_Round F64x2 high lane");
         end loop;
      end;
   end loop;
   if Failures = 0 then
      Put_Line ("PASS");
   else
      Put_Line ("FAILURES:" & Failures'Image);
      Ada.Command_Line.Set_Exit_Status (Ada.Command_Line.Failure);
   end if;
end Conversion_Tests;
